### ISSUE TITLE
webrtc-rs docker build failure

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/webrtc-interop#47]
@rainliu any ideas about the webrtc-rs docker duild failure? See, https://github.com/sipsorcery/webrtc-echoes/runs/3968597159?check_suite_focus=true.

**Comment by rainliu** [comment]
fixed in https://github.com/sipsorcery/webrtc-echoes/commit/272686f76a2df46d7d9d2ad0c228106520bd9d83
